name: ng_color_picker_example
description: Color picker example
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_components:
    git:
      url: https://github.com/dukefirehawk/angular_components/
      path: angular_components
      ref: migrated/bug-fix-1
  ng_color_picker:
    path: ../

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
  lints: ^1.0.1

