name: ng_color_picker
description: Simple and lightweight color picker component for AngularDart
version: 0.0.2
homepage: https://jodinathan.github.io/ng_color_picker/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_components:
    path: ../angular_components/angular_components
  build: ^2.1.1
  lib_colors:
    path: ../lib_colors
  sass_builder: ^2.1.4
  dispose: ^0.0.7
  stream_transform: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
  lints: ^1.0.1

