name: ng_color_picker
description: Simple and lightweight color picker component for AngularDart
version: 0.0.2
homepage: https://jodinathan.github.io/ng_color_picker/

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.3
  build: ^1.6.2
  lib_colors: ^1.0.17
  sass_builder: ^2.1.3
  dispose: ^0.0.5

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0

dependency_overrides:
  dispose:
    path: ../../guara.ci/imports/dispose
